# Generated by Django 5.0.4 on 2024-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(max_length=100)),
                ('harga', models.IntegerField(max_length=100)),
            ],
        ),
    ]
