# Generated by Django 5.0.4 on 2024-04-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jumlah',
        ),
    ]
