# Generated by Django 5.0.4 on 2024-05-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_watch', '0003_user_harga_user_jumlah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=100)),
                ('harga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_watch.harga')),
                ('jumlah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_watch.jumlah')),
            ],
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merek', models.CharField(max_length=100)),
                ('nama_pendiri', models.CharField(max_length=100)),
                ('tahun_berdiri', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=100)),
                ('tahun_peluncuran', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_negara', models.CharField(max_length=100)),
                ('mata_uang', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='managementwatch',
            name='merek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_watch.merek'),
        ),
        migrations.AddField(
            model_name='managementwatch',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_watch.model'),
        ),
        migrations.AddField(
            model_name='managementwatch',
            name='negara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_watch.negara'),
        ),
    ]
