# Generated by Django 5.0.4 on 2024-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_watch', '0004_harga_jumlah_managementwatch_merek_model_negara_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harga',
            old_name='harga',
            new_name='harga_jam',
        ),
        migrations.RenameField(
            model_name='jumlah',
            old_name='jumlah',
            new_name='jumlah_jam',
        ),
        migrations.AddField(
            model_name='harga',
            name='harga_baterai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harga',
            name='harga_tali',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jumlah',
            name='jumlah_baterai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jumlah',
            name='jumlah_tali',
            field=models.IntegerField(default=0),
        ),
    ]
