# Generated by Django 5.0.4 on 2024-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_watch', '0005_rename_harga_harga_harga_jam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='nama_pencipta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
