# Generated by Django 5.0.4 on 2024-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_watch', '0008_customuser_is_user_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
